from django.conf.urls import patterns, url


urlpatterns = patterns(
    '',
    url(r'^orders$', 'vendors.views.orders', name='orders'),
    url(r'^order/(?P<order_pk>\d+)/$', 'vendors.views.order', name='order'),
    url(r'^confirm\-accept\-order/(?P<order_pk>\d+)/$', 'vendors.views.confirm_accept_order',
        name='confirm_accept_order'),
    url(r'^accepted\-order/(?P<order_pk>\d+)/$', 'vendors.views.accepted_order', name='accepted_order'),
    url(r'^get\-latest\-orders$', 'vendors.views.get_latest_orders', name='get_latest_orders'),
    url(r'^orders\-to\-pick\-up$', 'vendors.views.orders_to_pick_up', name='orders_to_pick_up'),
    url(r'^orders\-to\-pick\-up\-pdf$', 'vendors.views.orders_to_pick_up_pdf', name='orders_to_pick_up_pdf'),
    url(r'^orders\-to\-drop\-off$', 'vendors.views.orders_to_drop_off', name='orders_to_drop_off'),
    url(r'^orders\-to\-drop\-off\-pdf$', 'vendors.views.orders_to_drop_off_pdf', name='orders_to_drop_off_pdf'),
    url(r'^order\-history$', 'vendors.views.order_history', name='order_history'),
    url(r'^postcodes\-served$', 'vendors.views.postcodes_served', name='postcodes_served'),
    url(r'^operating\-hours$', 'vendors.views.operating_hours', name='operating_hours'),
    url(r'^contact\-details\-and\-notifications$', 'vendors.views.contact_details_and_notifications',
        name='contact_details_and_notifications'),
    url(r'^issue\-raised/(?P<order_pk>\d+)/$', 'vendors.views.issue_raised', name='issue_raised'),
    url(r'^throw\-orders\-back\-in\-pool$', 'vendors.views.throw_orders_back_in_pool',
        name='throw_orders_back_in_pool'),
    url(r'^orders\-to\-tag$', 'vendors.views.orders_to_tag', name='orders_to_tag'),
    url(r'^order\-payments$', 'vendors.views.order_payments', name='order_payments'),
    url(r'^upcoming$', 'vendors.views.upcoming', name='upcoming'),
    url(r'^upcoming\-pdf$', 'vendors.views.upcoming_pdf', name='upcoming_pdf'),
    url(r'^expected\-back\-clean\-only$', 'vendors.views.expected_back_clean_only', name='expected_back_clean_only'),
    url(r'^expected\-back\-clean\-only\-all$', 'vendors.views.expected_back_clean_only_all',
        name='expected_back_clean_only_all'),
    url(r'^expected\-back\-clean\-only\-confirm$', 'vendors.views.expected_back_clean_only_confirm',
        name='expected_back_clean_only_confirm'),
    url(r'^default\-prices$', 'vendors.views.default_prices', name='default_prices'),
    url(r'^pdf/(?P<order_pk>\d+)$', 'vendors.views.pdf_order', name='pdf_order'),
    url(r'^weekly-upcoming$', 'vendors.views.weekly_upcoming', name='weekly_upcoming'),
    url(r'^update-order/(?P<order_pk>\d+)/$', 'vendors.views.update_order', name='update_order'),
)
